# -*- coding: utf-8 -*-
"""
Created on Wed Mar 26 19:34:08 2025

@author: sai.venkat
"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# We can add a constant value 
# in this data set profit is independent variable i.e y
# in this data set all other are dependent variable i.e x1,x2,x3
# y=m1x1+m2x2+m3x3+c-->Multi linear regression model

# Use case  Identify good stocks for investment
dataset=pd.read_csv(r"C:\Users\sai.venkat\OneDrive\DataScience\Python\PYTHON_BIGINNER\Libraries\Machine Learning\Multiple Linear Regression\Investment.csv")
X=dataset.iloc[:,:-1]  # independent variable
Y=dataset.iloc[:,4]  #dependent variable
 # Transformer  
X=pd.get_dummies(X,dtype=int)  # replaces categorical data with numerical values as explained in eda

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)


# Model Building

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)


Y_Pred=regressor.predict(X_test)

m_slope=regressor.coef_
print(m_slope)

c_intercept=regressor.intercept_
print(c_intercept)


# adding  a column full as 1 to understand what is right attribute 1 plays as constant in the equation..
#X=np.append(arr=np.ones((50,1)).astype(int), values=X,axis=1)

# Post Class Test with the intercept value obtained
new_column_interceptCalculated = np.full((X.shape[0], 1), c_intercept)
X= np.append(X, new_column_interceptCalculated, axis=1)


import statsmodels.api as sm
# this contains statistics equation to pass data between stats and ml

# OLS --ordinary least squares --Diff btw Y pred and Y test-->This gives residuals 

# we are selecting only 6 cols out of 7 using one hot encoder transformer 
x_opt=X[:,[0,1,2,3,4,5,6]]

regressor_OLS=sm.OLS(endog=Y,exog=x_opt).fit()
regressor_OLS.summary()


# since in x3 p>t col value is >0.05 in beside table eliminate 3 [where p max value shd be 0.05]
# repeat these steps till we get value< 0.05
# similarly implement the same for other attributes finally we will be left with x1


x_opt=X[:,[0,1,2,4,6]]
regressor_OLS=sm.OLS(endog=Y,exog=x_opt).fit()
regressor_OLS.summary()




x_opt=X[:,[0,1,2,6]]
regressor_OLS=sm.OLS(endog=Y,exog=x_opt).fit()
regressor_OLS.summary()


x_opt=X[:,[0,2,6]]
regressor_OLS=sm.OLS(endog=Y,exog=x_opt).fit()
regressor_OLS.summary()

x_opt=X[:,[0,6]]
regressor_OLS=sm.OLS(endog=Y,exog=x_opt).fit()
regressor_OLS.summary()





# Feature Elimination-->Technique to eliminate feature
# Reccursive Elimination can be acheived by forward or backward elimination process.Any 1 can be choosen
# Here we have 6 features how to eliminate 5 and keep only 1??
# Backward Elimination : p-value-(0.05)>significance  value generated by model reject the null hypothesis (remove the attribute/feature)
# Forward Elimination : significance  value generated by modelreject the null hypothesis (remove the attribute/feature)>p-value-(0.05)






