# -*- coding: utf-8 -*-
"""Jan 6th.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1thds2OFSKznUAB91QvGbLwBJ28aNCue7
"""

10//5 #int

10/5  #float

" Artificial intelligence (AI), in its broadest sense, is intelligence exhibited by machines, particularly computer systems. It is a field of research in computer science that develops and studies methods and software
that enable machines to perceive their environment and use learning and intelligence to take"

'''  Artificial intelligence (AI), in its broadest sense, is intelligence exhibited by machines, particularly computer systems. It is a field of research in computer science that develops and studies methods and software that enable machines to perceive their environment and
 use learning and intelligence to take'''

S='''  Sai Ram  Venkat'''
print(S)

"Sai Ram Venkat Geni AI Training" #string works with 'Sai', "Sai Ram",''' Sai Dp World''''

''' Sai Ram Dpworld '''