# # -*- coding: utf-8 -*-
# """Jan 7th.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/17ZTssP1jSfYAloMru48hQmTVFQhk8hhJ
# """

# import sys
# sys.version

# import keyword
# keyword.kwlist

# len(keyword.kwlist)

# A=100

# A

# type(A)

# id(A)

# x=89.08
# type(x)
# id(x)

# Age=30
# print(Age)

# Fname="sai";
# LName="Ram";
# FullName=Fname+LName;
# print(FullName);

# Length=10
# Width=5
# Area=Length*Width
# print(Area)

# #indentation is mandatory for function
def area(l,w):
    return l*w
print(area(5,10))