# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H801aUu31RFzPnUYvxX_3c_jDfhsa_GL
"""

import streamlit as st
from googletrans import Translator
import pyttsx3
import tempfile
import os

st.title("Multilingual Text Converter with Voice")

# Input text
text_input = st.text_area("Enter text to convert")

# Language options
languages = {
    "English": "en",
    "Spanish": "es",
    "French": "fr",
    "German": "de",
    "Hindi": "hi",
    "Chinese": "zh-cn",
    "Arabic": "ar",
    "Russian": "ru"
}

target_language = st.selectbox("Choose target language", list(languages.keys()))
voice_gender = st.radio("Choose voice gender", ["Male", "Female"])

if st.button("Translate and Speak"):
    if not text_input.strip():
        st.warning("Please enter text first.")
    else:
        # Translate text
        translator = Translator()
        translated = translator.translate(text_input, dest=languages[target_language])
        translated_text = translated.text
        st.success(f"Translated Text ({target_language}):")
        st.write(translated_text)

        # Set up TTS
        engine = pyttsx3.init()
        voices = engine.getProperty('voices')

        # Set voice gender
        if voice_gender == "Male":
            for voice in voices:
                if "male" in voice.name.lower():
                    engine.setProperty('voice', voice.id)
                    break
        else:
            for voice in voices:
                if "female" in voice.name.lower():
                    engine.setProperty('voice', voice.id)
                    break

        # Save audio to temp file
        with tempfile.NamedTemporaryFile(delete=False, suffix=".mp3") as tf:
            temp_path = tf.name
            engine.save_to_file(translated_text, temp_path)
            engine.runAndWait()

        # Play audio
        st.audio(temp_path, format="audio/mp3")

        # Download link
        with open(temp_path, "rb") as file:
            st.download_button(
                label="Download Audio",
                data=file,
                file_name="translated_audio.mp3",
                mime="audio/mp3"
            )

        # Clean up
        engine.stop()
        os.remove(temp_path)